### ISSUE TITLE
can't read chromium button

### ISSUE THREAD

**Issue by neuroloops** [Fausto-Korpsvart/Tokyo-Night-GTK-Theme#51]
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/56033812/af1fb3ec-67ac-46d3-8400-c8d9f74fc795)

any reason why this line is commented in gtk3.0/gtk.css

```css
window.background.chromium treeview.view.cell:selected:focus {
  background-color: #a9b1d6;
  /* color: rgba(0, 0, 0, 0.87); */
}
```

uncommenting it, solves the problem
![image](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme/assets/56033812/94fa0ff1-f0d2-467d-9e38-ed8ee0000688)
